kind: pipeline
type: docker
name: Gamemaster

steps:
- name: publish-docker
  image: plugins/docker
  network_mode: registry-network
  settings:
    dockerfile: service/Gamemaster/Dockerfile
    context: service/Gamemaster
    repo: registry:5000/gamemaster
    registry: registry:5000
    insecure: true

- name: publish-service-sources
  image: alpine/git
  environment:
    SSH_KEY:
      from_secret: github_bot_ssh_key
  commands:
    # write the ssh key to disk
    - mkdir /root/.ssh
    - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa

    # add github to known hosts
    - touch /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/known_hosts
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null

    # push service changes
    - git clone git@github.com:enowars/enowars4-vulnbox-services.git
    - cd enowars4-vulnbox-services
    - rm -rf gamemaster/
    - cp -r ../service/ gamemaster/
    - git add gamemaster/
    - git commit -m 'Update gamemaster service' || true
    - git push origin HEAD:master || true

    # push checker changes
    - cd -
    - git clone git@github.com:enowars/enowars4-vulnbox-checkers.git
    - cd enowars4-vulnbox-checkers
    - rm -rf gamemaster/
    - cp -r ../checker/ gamemaster/
    - git add gamemaster/
    - git commit -m 'Update gamemaster checker' || true
    - git push origin HEAD:master || true

- name: trigger-vm-image-creation
  image: plugins/downstream
  settings:
    server: https://droneci.sect.tu-berlin.de
    token:
      from_secret: trigger_token
    fork: true
    repositories:
      - enowars/Enowars4DevOps@master

trigger:
  branch:
  - master
  event:
  - push
