version: '3.4'

services:
  gamemaster:
    build:
      context: Gamemaster
      dockerfile: Dockerfile
    environment:
      - DATABASE_DOMAIN=postgres
    ports:
      - "8001:80"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker