version: '3.4'

services:
  gamemaster:
    build:
      context: Gamemaster
      dockerfile: Dockerfile
    environment:
      - DATABASE_DOMAIN=postgres
    ports:
      - "8001:80"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    shm_size: 256MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 10