version: '3'
services:
  gamemaster-checker:
    build:
      context: GamemasterChecker
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - USE_ELK=true
    ports:
      - "8000:80"
  mongodb:
    image: mongo
