version: '3.4'

services:
#  enolauncher:
#    environment:
#      - DATABASE_DOMAIN=enopostgres
#    build:
#      context: .
#      dockerfile: EnoLauncher/Dockerfile
#    volumes:
#      - ./ctf.json:/app/ctf.json
  mongodb:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"