version: '3'
services:
  gamemaster-checker:
    build: .
    ports:
      - 8000:8080
  mongodb:
    image: mongo
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"