version: '3'
services:
  gamemaster-checker:
    build: .
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - USE_ELK=true
    ports:
      - "127.0.0.1:8000:80"
  mongodb:
    image: mongo
